import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[env]
TERM = "alacritty"
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[window]
opacity = 0.7
decorations = "full"

  [window.padding]
  x = 10
  y = 0

[font]
size = 13.0

  [font.normal]
  family = "monospace"
  style = "Regular"
